### ISSUE TITLE
Found bug: Duplicates in manifesto database

### ISSUE THREAD

**Issue by cliedl** [cliedl/parl_AI#5]
Code to reproduce: 

`DATABASE_DIR_MANIFESTOS = "../../data/manifestos/chroma"
import sys
sys.path.append("..")

from database.vector_database import VectorDatabase
from models.embedding import ManifestoBertaEmbeddings

embedding_model = ManifestoBertaEmbeddings()

db_manifestos = VectorDatabase(
    data_path="../data/manifestos",
    embedding_model=embedding_model,
    database_directory=DATABASE_DIR_MANIFESTOS,
    source_type="manifestos")
    
query = "Wie positionieren sich die verschiedenen Parteien zum Thema Erhöhung der Verteidigungsausgaben im Kontext gemeinsamer europäischer Sicherheitsinteressen?"

res = db_manifestos.database.similarity_search(query, 6, filter={"party": "fdp"})
print(res)
`

Output: 
<img width="1159" alt="Screenshot 2024-03-15 at 09 59 52" src="https://github.com/cliedl/parl_AI/assets/45002847/8e5c81b8-dcd7-487c-b94c-2060c3b1a744">

**Comment by Aneifer** [comment]
Der Fehler liegt evtl. in verctor database, wenn die DB kreiert wird
Das Modell findet dadurch weniger Dokumente, Qualität des Outputs schlechter. 

# 1) Chroma upserts:
upsert items. new items will be added, existing items will be updated.
collection.upsert(
    ids=["id1", "id2", "id3", ...],
    embeddings=[[1.1, 2.3, 3.2], [4.5, 6.9, 4.4], [1.1, 2.3, 3.2], ...],
    metadatas=[{"chapter": "3", "verse": "16"}, {"chapter": "3", "verse": "5"}, {"chapter": "29", "verse": "11"}, ...],
    documents=["doc1", "doc2", "doc3", ...],
)

https://docs.trychroma.com/api-reference


# 2) Langchain similarity threshold:
similarity_fn 
Similarity function for comparing documents. Function expected to take as input two matrices (List[List[float]]) and return a matrix of scores where higher values indicate greater similarity.

similarity_threshold
Threshold for determining when two documents are similar enough to be considered redundant.

https://api.python.langchain.com/en/latest/document_transformers/langchain_community.document_transformers.embeddings_redundant_filter.EmbeddingsRedundantFilter.html#

**Comment by Aneifer** [comment]
# Spur der Duplikate:

In der source wird klar, es gibt zwei verschiedene paths:
1) ../..data
2) ../ data

![Image](https://github.com/cliedl/parl_AI/assets/132136730/f840d86a-f5f4-42ee-a74f-d76978baf716)

Diese unterschiedliche Schreibweise gibt es gleichzeitig angewandt nur in den Notebooks test und balanced_retrieval_example

Hypothese: 
Ggf. sind mehrere Fehler gleichzeitig passiert
1) Könnten mehr Duplikate beim Durchlaufen von balanced_retrieval_example und test entstanden sein, dadurch das bei dir Chris automatisch das sys vertauscht wird, bevor die Klasse VectorDatabase importiert werden kann?
Als ich am Freitag das gepushte balanced_retrieval_example bekommen habe, war das sys hinter der Importierung des Moduls, das notebook war aber "gerunned".

2) Ich habe eine neue Datenbank erstellt und habe dann das test notebook gerunned, wie ihr oben seht habe ich dann triplettes in der source gehabt. Es hat dann angezeigt, das ich in der Manifesto Datenbank etwa 68 % Duplikate hatte, die Anzahl der Duplikate könnte also durch das runnen des test-notebooks gestiegen sein.

Zu untersuchen:
- Wenn die Datenbank schon existiert und dann das notebook create_database runned, wird tatsächlich eine neue Datenbank erstellt oder Dokumente zur bestehenden hinzugefügt?
- Werden die Duplikate durch den PDF loader in vector_database.py generiert?
- Was ist tatsächlich in docs in vector_database.py enthalten?
