### ISSUE TITLE
Which similarity should we use - default is euclidean distance

### ISSUE THREAD

**Issue by cliedl** [cliedl/parl_AI#6]
Default similarity in database.similarity_search seems to be euclidian distance:
https://api.python.langchain.com/en/latest/_modules/langchain_community/vectorstores/chroma.html#Chroma.similarity_search:

<img width="780" alt="Screenshot 2024-03-15 at 10 02 57" src="https://github.com/cliedl/parl_AI/assets/45002847/f4887a27-375c-4d19-bc0b-aebb57ca8860">

Intuitively, cosine, makes more sense

**Comment by Aneifer** [comment]
Ggf. selbst schreiben
